/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { AppInfo } from './AppInfo';

export const APP_LIST_DATA: AppInfo[] = [
  new AppInfo($r("app.media.grid_exchange_ic_public_app1"), 'APP1'),
  new AppInfo($r("app.media.grid_exchange_ic_public_app2"), 'APP2'),
  new AppInfo($r("app.media.grid_exchange_ic_public_app3"), 'APP3'),
  new AppInfo($r("app.media.grid_exchange_ic_public_app4"), 'APP4'),
  new AppInfo($r("app.media.grid_exchange_ic_public_app5"), 'APP5'),
  new AppInfo($r("app.media.grid_exchange_ic_public_app6"), 'APP6'),
  new AppInfo($r("app.media.grid_exchange_ic_public_app7"), 'APP7'),
  new AppInfo($r("app.media.grid_exchange_ic_public_app8"), 'APP8'),
  new AppInfo($r("app.media.grid_exchange_ic_public_app9"), 'APP9'),
  new AppInfo($r("app.media.grid_exchange_ic_public_app10"), 'APP10'),
  new AppInfo($r("app.media.grid_exchange_ic_public_app11"), 'APP11'),
  new AppInfo($r("app.media.grid_exchange_ic_public_app12"), 'APP12'),
  new AppInfo($r("app.media.grid_exchange_ic_public_app13"), 'APP13')
]